import type { ResolvedDesign } from "../types";

/**
 * Generate TypeScript type definitions and a typed token object for the design.
 */
export function generateTypeDefinitions(resolved: ResolvedDesign): string {
  return `// ══════════════════════════════════════════════════════════
// Design Tokens — TypeScript Definitions
// Generated by Ditto
// ══════════════════════════════════════════════════════════

export interface DesignTokens {
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    surface: string;
    textPrimary: string;
    textSecondary: string;
    textMuted: string;
    border: string;
    success: string;
    warning: string;
    error: string;
  };
  fonts: {
    heading: string;
    body: string;
    mono: string;
    weightHeading: number;
    weightBody: number;
  };
  text: {
    xs: string;
    sm: string;
    base: string;
    lg: string;
    xl: string;
    "2xl": string;
    "3xl": string;
    "4xl": string;
  };
  spacing: {
    xs: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
    "2xl": string;
  };
  radius: {
    sm: string;
    md: string;
    lg: string;
    full: string;
  };
  shadows: {
    sm: string;
    md: string;
    lg: string;
  };
  lineHeight: {
    tight: string;
    normal: string;
    relaxed: string;
  };
}

export const tokens: DesignTokens = {
  colors: {
    primary: "${resolved.colorPrimary}",
    secondary: "${resolved.colorSecondary}",
    accent: "${resolved.colorAccent}",
    background: "${resolved.colorBackground}",
    surface: "${resolved.colorSurface}",
    textPrimary: "${resolved.colorTextPrimary}",
    textSecondary: "${resolved.colorTextSecondary}",
    textMuted: "${resolved.colorTextMuted}",
    border: "${resolved.colorBorder}",
    success: "${resolved.colorSuccess}",
    warning: "${resolved.colorWarning}",
    error: "${resolved.colorError}",
  },
  fonts: {
    heading: "'${resolved.fontHeading}', system-ui, sans-serif",
    body: "'${resolved.fontBody}', system-ui, sans-serif",
    mono: "'${resolved.fontMono}', ui-monospace, monospace",
    weightHeading: ${resolved.fontWeightHeading},
    weightBody: ${resolved.fontWeightBody},
  },
  text: {
    xs: "${resolved.textXs}",
    sm: "${resolved.textSm}",
    base: "${resolved.textBase}",
    lg: "${resolved.textLg}",
    xl: "${resolved.textXl}",
    "2xl": "${resolved.text2xl}",
    "3xl": "${resolved.text3xl}",
    "4xl": "${resolved.text4xl}",
  },
  spacing: {
    xs: "${resolved.spacingXs}",
    sm: "${resolved.spacingSm}",
    md: "${resolved.spacingMd}",
    lg: "${resolved.spacingLg}",
    xl: "${resolved.spacingXl}",
    "2xl": "${resolved.spacing2xl}",
  },
  radius: {
    sm: "${resolved.radiusSm}",
    md: "${resolved.radiusMd}",
    lg: "${resolved.radiusLg}",
    full: "${resolved.radiusFull}",
  },
  shadows: {
    sm: "${resolved.shadowSm}",
    md: "${resolved.shadowMd}",
    lg: "${resolved.shadowLg}",
  },
  lineHeight: {
    tight: "${resolved.lineHeightTight}",
    normal: "${resolved.lineHeightNormal}",
    relaxed: "${resolved.lineHeightRelaxed}",
  },
};
`;
}
